"""Create kanban boards, columns, and cards tables

Revision ID: c6f281db0d05
Revises: d6508aeb50b3
Create Date: 2025-09-30 11:30:20.796323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f281db0d05'
down_revision: Union[str, Sequence[str], None] = 'd6508aeb50b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
